set_property SRC_FILE_INFO {cfile:C:/Users/admin/fpga/rv32e/vivado/Rv32I.srcs/constrs_1/new/rv32e.xdc rfile:../../../Rv32I.srcs/constrs_1/new/rv32e.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports clk_p]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports flash_cs_n]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports ram_cs_n]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22 [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22 [get_ports spi_sclk]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {gpio_out[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {gpio_out[1]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {gpio_out[2]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {gpio_out[3]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {gpio_out[4]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -min -add_delay 0.500 [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -max -add_delay 3.000 [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -min -add_delay 0.500 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -max -add_delay 3.000 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -min -add_delay 0.000 [get_ports {gpio_out[*]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -max -add_delay 3.000 [get_ports {gpio_out[*]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -min -add_delay 0.500 [get_ports flash_cs_n]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -max -add_delay 3.000 [get_ports flash_cs_n]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -min -add_delay 0.500 [get_ports ram_cs_n]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -max -add_delay 3.000 [get_ports ram_cs_n]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -min -add_delay 0.500 [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks -of_objects [get_pins clk_ins/inst/mmcm_adv_inst/CLKOUT4]] -max -add_delay 3.000 [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports error_flag]
